Support demos with client and verify basic functionalities
fujitatomoya/ros2_persist_parameter_server pull request #5
Opened 2020-09-28 10:30 UTC by Ada-King

@fujitatomoya 
Please have a review, thanks.

2020-09-28 12:34 UTC, fujitatomoya commented
close https://github.com/fujitatomoya/ros2_persist_parameter_server/issues/4

2020-09-28 12:35 UTC, fujitatomoya commented
@Ada-King 

thanks, i will look into it.

2020-09-28 12:36 UTC, fujitatomoya commented
either @iuhilnehc-ynos or @Barry-Xu-2018, could you help us to review when you got time?

2020-09-29 01:56 UTC, Barry-Xu-2018 commented
@fujitatomoya 

I have checked this commit.  
 @iuhilnehc-ynos please check this commit.

2020-09-29 09:25 UTC, iuhilnehc-ynos requested changes
@Ada-King @fujitatomoya @Barry-Xu-2018 

I left some comments, please check them.

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/src/main.cpp
> +        throw SetErrorException();
If it throws Exception from here, can we get the failure result?

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/src/main.cpp
> +  return 0;
If there is an exception thrown, do we still expect the result is 0?

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/src/main.cpp
> +    RCLCPP_ERROR(get_logger("rcl"), "unexpectedly failed: %s", e.what());
I think the logger name `rcl` might make users confused because this message `unexpectedly failed: xxx` is not from `rcl` library.

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/src/main.cpp
> +    test_client->get_result();
If `get_result` returns nothing, we might rename it with `print_result`

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/include/persist_parameter_client.hpp
> +using namespace rclcpp::node_interfaces::detail;
Is it necessary to use `rclcpp::node_interfaces::detail`?

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/include/persist_parameter_client.hpp
> +using namespace rclcpp;
I think we don't expect `using namespace rclcpp;` in C++ header file. 
BTW, if you already use it, why to use `rclcpp::` below?

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/launch/test.launch.py
> +respawn_delay = 0.0
The default value of `respawn_delay` is `0.0`, I think you don't need to define it if using `0.0`.

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/src/main.cpp
> +#include "persist_parameter_client.hpp"
Unless it's the source file related to its header file, we include a non-standard header file after c and c++ standard files.

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/src/main.cpp
> +  const char * what () const throw () {
please use `noexcept` instead of `throw`.

```
virtual const char* what() const throw();  (until C++11)
virtual const char* what() const noexcept;  (since C++11)
```

But I would recommend using `std::runtime_error` because these exceptions seems a runtime error, such as

```
class InvalidNodeError : public std::runtime_error
{
public:
  InvalidNodeError()
  : std::runtime_error("node is invalid") {}
};
```

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/include/persist_parameter_client.hpp
> +        RCLCPP_INFO(this->get_logger(), "SET OPERATION : Failed to set parameter: %s", result.reason.c_str());
If failure happened, it prints "Failed" and then continues to output "successfully".
I think you might want to `return ret` after this "Failed" log.

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/include/persist_parameter_client.hpp
> +  inline void format_array_output(std::stringstream & ss, const std::vector<ValueType> & cont)
If we just use `output stream` here, please use `std::ostreamstream`.
and why named with `cont`?

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/include/persist_parameter_client.hpp
> +      std::chrono::seconds timeout = 5s;
Maybe we could use `wait_for_service(5s)` directly.

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/start.py
> +        program_name = 'server'
This script will kill all processes named by `server`, it seems a little dangerous.

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/CMakeLists.txt
> +    src/main.cpp
Please use the same indent space (2 is OK), the same as below.

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/src/main.cpp
> +	  test_client->do_read_and_check("new_string", nullptr, "i. Test New Added Normal Parameter Not Stores To File");
indent

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/src/main.cpp
> +        RCLCPP_INFO(get_logger("client"), "%s : \t\t%s", res.first.c_str(), res.second?"PASS":"NOT PASS");
I think we could use "%-60s%16s" instead, and also update the README.

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/src/main.cpp
> +      auto pair = result_map.insert(std::make_pair<std::string, bool>(std::move(key), std::move(value)));
That's interesting, why to use `std::move` for `bool`?
And I think we could use insert `({key, value})` instead of `std::make_pair`

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on README.md
> +!!NOTE After the test is completed, you need to press `ctrl-c` to stop process manually.
only two `!` here compared with three `!` above?

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/package.xml
> +  <version>0.0.0</version>
1.0.0

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/src/persist_parameter_client.cpp
> +        }
It seems just a `debug` log here. Is it necessary for the test ?

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on README.md
> +[ros2-2] [INFO] [1601285807.447188102] [client]: a. Read Normal Parameter : 		PASS
Right align for "PASS/NOT PASS"

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/CMakeLists.txt
> +endif()
Remove these if we don't use them.

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/src/main.cpp
> +      RCLCPP_INFO(get_logger("client"), "First read the initial value of parameter : ");
Maybe you could define `rclcpp::Logger("client")` at the beginning, or use `test_client->get_logger()`

2020-09-29 09:25 UTC, iuhilnehc-ynos commented on client_demo/src/persist_parameter_client.cpp
> +  parameter = sync_param_client_->get_parameters(param_vec);
Maybe you could just use `get_parameters({param_name})`;

2020-09-30 06:39 UTC, Ada-King commented on client_demo/src/main.cpp
> +      auto pair = result_map.insert(std::make_pair<std::string, bool>(std::move(key), std::move(value)));
> That's interesting, why to use std::move for bool?

Cause the parameter of map.insert accepts rvalue reference, so i use std::move convert the lvalue to rvalue.

> And I think we could use insert ({key, value}) instead of std::make_pair

Agree, it's better.

2020-09-30 06:39 UTC, Ada-King commented on client_demo/src/persist_parameter_client.cpp
> +        }
It has no effect on the result, i keep it just to ouput some information to make the test process clear.

2020-09-30 07:01 UTC, iuhilnehc-ynos commented on client_demo/src/main.cpp
> +      RCLCPP_INFO(get_logger("client"), "First read the initial value of parameter : ");
Using `rclcpp::get_logger("client")`  will create `rclcpp::Logger` object every time.

2020-09-30 07:06 UTC, iuhilnehc-ynos reviewed
Why just close them?

2020-09-30 07:06 UTC, iuhilnehc-ynos commented on client_demo/include/persist_parameter_client.hpp
> +using namespace rclcpp;
?

2020-09-30 07:06 UTC, iuhilnehc-ynos commented on client_demo/include/persist_parameter_client.hpp
> +using namespace rclcpp::node_interfaces::detail;
?

2020-09-30 08:30 UTC, iuhilnehc-ynos approved these changes

2020-10-05 07:59 UTC, fujitatomoya requested changes

2020-10-05 07:59 UTC, fujitatomoya commented on README.md
> +# Use Client Demo
```suggestion
# Test
```

this goes to directory and file names.

2020-10-05 07:59 UTC, fujitatomoya commented on README.md
> +The client demo verifies the following functions
These samples verify the following functions.

2020-10-05 07:59 UTC, fujitatomoya commented on README.md
> +!!!NOTE The client demo provided does not support the use of the specified parameter name, it only demonstrates and verifies the basic functions of the parameter server.
`The client demo provided does not support the use of the specified parameter name`, I am not sure what this is about. This samples are verification usage, so I think we could delete this line?

2020-10-05 07:59 UTC, fujitatomoya commented on README.md
> +The build steps are similar to the above build step, except that you need to install ros2 launch package with `respawn` feature support, which is only support in master branch now.
I think that procedure can be shown with master source build procedure. so we can delete this procedure since that is already described above.

2020-10-05 07:59 UTC, fujitatomoya commented on README.md
> +start.py is the entry for test.
please use link instead of text, it would be better to jump the file to see what it does in browser.

2020-10-05 07:59 UTC, fujitatomoya commented on README.md
> +The phenomenon as below
```suggestion
All of the test is listed with result as following
```

2020-10-05 07:59 UTC, fujitatomoya commented on README.md
> +```
```
[ros2-2] [INFO] [1601879268.221875123] [client]: ***************************************************************************
[ros2-2] [INFO] [1601879268.221886904] [client]: *********************************Test Result*******************************
[ros2-2] [INFO] [1601879268.221896324] [client]: a. Read Normal Parameter                                     :         NOT PASS
[ros2-2] [INFO] [1601879268.221908034] [client]: b. Read Persistent Parameter                                 :         NOT PASS
[ros2-2] [INFO] [1601879268.221930384] [client]: c. Modify Existed Normal parameter                           :             PASS
[ros2-2] [INFO] [1601879268.221940164] [client]: d. Modify Existed Persistent parameter                       :             PASS
[ros2-2] [INFO] [1601879268.221949584] [client]: e. Add New Normal parameter                                  :             PASS
[ros2-2] [INFO] [1601879268.221958934] [client]: f. Add New Persistent parameter                              :             PASS
[ros2-2] [INFO] [1601879268.221968605] [client]: g. Test Normal Parameter Not Stores To File                  :         NOT PASS
[ros2-2] [INFO] [1601879268.221978105] [client]: h. Test Persistent Parameter Stores To File                  :             PASS
[ros2-2] [INFO] [1601879268.221987905] [client]: i. Test New Added Normal Parameter Not Stores To File        :         NOT PASS
[ros2-2] [INFO] [1601879268.221997275] [client]: j. Test New Added Persistent Parameter Stores To File        :             PASS
```

some tests are not successfully done.

2020-10-05 07:59 UTC, fujitatomoya commented on client_demo/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.5)
change directory name into test

2020-10-05 07:59 UTC, fujitatomoya commented on client_demo/src/main.cpp
> +      : std::runtime_error("Not find server"){}
```suggestion
      : std::runtime_error("cannot connect to server"){}
```

2020-10-05 07:59 UTC, fujitatomoya commented on client_demo/src/main.cpp
> + * If not, then throw an exception to terminate the endless waiting.
```suggestion
 * If timeout, then throw an exception to terminate the endless waiting.
```

2020-10-05 07:59 UTC, fujitatomoya commented on client_demo/package.xml
> +  <name>client_demo</name>
```suggestion
  <name>ros2_persistent_parameter_server_test</name>
```

2020-10-05 07:59 UTC, fujitatomoya commented on client_demo/start.py
> +def restart_server():
I am not convinced with this name, it should be more like `kill_server` because it does not actually restart the server but launch system.

2020-10-05 07:59 UTC, fujitatomoya commented on client_demo/start.py
> +                    print("parameter server restart successfully")
```suggestion
                    print("parameter server is killed successfully")
```

2020-10-05 07:59 UTC, fujitatomoya commented on client_demo/start.py
> +        print("parameter server restart now...")
```suggestion
        print("parameter server is about to be killed...")
```

2020-10-05 07:59 UTC, fujitatomoya commented on client_demo/start.py
> +        print("parameter server restart failed")
```suggestion
        print("parameter server cannot be killed")
```

2020-10-05 07:59 UTC, fujitatomoya commented on client_demo/src/main.cpp
> +    * Parameter server is launched with file `/tmp/parameter_server.yaml`, in this file, parameter `a_string` is defined
This whole test is expected to issued after `/tmp/parameter_server.yaml` is copied to /tmp. that means it should be able to copy and reset the `/tmp/parameter_server.yaml` at initialization. maybe creating temporary directory would be better since `/tmp/parameter_server.yaml` would be used by user.

2020-10-05 07:59 UTC, fujitatomoya commented on client_demo/src/main.cpp
> +  }catch(const SetOperationError & e) {
```suggestion
  } catch (const rclcpp::exceptions::RCLError & e) {
    ret_code = -1;
    RCLCPP_ERROR(test_client->get_logger(), "unexpectedly failed: %s", e.what());
  } catch (const NoServerError & e) {
    ret_code = -2;
    RCLCPP_ERROR(test_client->get_logger(), "unexpectedly failed: %s", e.what());
  } catch (const SetOperationError & e) {
```

code style.

2020-10-05 07:59 UTC, fujitatomoya commented on client_demo/start.py
> +os.system(launchCmd)
I would print the notification that user needs to shutdown with `Ctrl-C`

2020-10-05 07:59 UTC, fujitatomoya commented on client_demo/start.py
> +                if "install/parameter_server/lib/parameter_server" in path.exe():
this does not work when it uses `colcon build --symlink-install`, i think that most common case is this test will be used on mainline with source build with `colcon build --symlink-install`. what do you think? the following solves this problem.

```suggestion
                if "install/parameter_server/lib/parameter_server" or "parameter_server/server" in path.exe():
```

2020-10-12 05:56 UTC, Ada-King commented on README.md
> +!!!NOTE The client demo provided does not support the use of the specified parameter name, it only demonstrates and verifies the basic functions of the parameter server.
Sure.

2020-10-12 05:57 UTC, Ada-King commented on README.md
> +```
The original value of variable `a_string` is assumed to be `Hello world`. 
e.g.
```
...
a_string: Hello world
    pi: 3.14
    some_lists:
      some_integers: [1, 2, 3, 4]
    persistent:
      a_string: Hello world
...
```

2020-10-12 05:58 UTC, Ada-King commented on client_demo/src/main.cpp
> +    * Parameter server is launched with file `/tmp/parameter_server.yaml`, in this file, parameter `a_string` is defined
Ok, i will create a temporary diretory `/tmp/test` and add the related descriptions in the document.

2020-10-12 05:58 UTC, Ada-King commented on client_demo/start.py
> +os.system(launchCmd)
Ok.

2020-10-12 05:59 UTC, Ada-King commented on client_demo/start.py
> +                if "install/parameter_server/lib/parameter_server" in path.exe():
Make sense to me,  already changed.

2020-10-12 06:05 UTC, Ada-King commented on README.md
> +The build steps are similar to the above build step, except that you need to install ros2 launch package with `respawn` feature support, which is only support in master branch now.
Ok, i will create a link to above description and add some additional descriptions as needed.

2020-10-12 07:57 UTC, fujitatomoya approved these changes

2020-10-12 07:57 UTC, fujitatomoya commented on README.md
>  ## Build
maybe we can delete this section in the future with description this supported from ros:foxy.

2020-10-12 07:59 UTC, merged